---
title: "Raw likelihood & gradient"
author: "Ami Sheth"
date: "2022-12-21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Libraries

```{r}
library(Matrix)
library(mvtnorm)
library(MASS)
library(invgamma)
library(truncnorm)
library(tidyverse)
library(gridExtra)
```

### Raw likelihood 

```{r}
sum_r2 <- function(D_latent, D, sigma, band.no){
  n <- dim(D)[1]
  SSR_val = 0
  logsum = 0
  pad <- matrix(NA, nrow = n, ncol = band.no)
  D_latent_pad <- cbind(D_latent, pad)
  D_pad <- cbind(D, pad)
  
  for (i in 1:n){
    for (j in 1:band.no){
      SSR_val = sum(SSR_val, (D_pad[i, i + j] - D_latent_pad[i, i + j])^2, na.rm = TRUE)
      stat = D_latent_pad[i, i + j] / sqrt(sigma)
      logsum = sum(logsum, log(pnorm(stat)), na.rm = TRUE)
    }
  }
  r = SSR_val/(2 * sigma) + logsum
  return(r)
}
```

```{r}
s_bmds_ll2 <- function(sigma, D, latent, band.no){ 
  # latent variables (nxk), observed distance matrix D (nxn), sigma^2
  D_latent <- as.matrix(dist(latent, diag = TRUE, upper = TRUE))
  n <- dim(D_latent)[1]
  m <- n * band.no - band.no * (band.no + 1) / 2  
  term1 <- (m / 2) * log(sigma)
  term2 <- sum_r2(D_latent, D, sigma, band.no)
  loglik <- -(term1 + term2)
  return(loglik)
}
```

### Raw gradient

```{r}
s_grad <- function(sigma, D, latent, band.no) {
  # padding to prevent errors
  dims <- dim(latent)[2]
  n <- dim(latent)[1]
  D_latent <- as.matrix(dist(latent, diag = TRUE, upper = TRUE))
  
  pad <- matrix(NA, nrow = n, ncol = band.no) # add padding column-wise
  pad2 <- matrix(NA, nrow = band.no, ncol = dims) # add padding row-wise
  
  D_latent_spad <- cbind(D_latent, pad) # padding to the right of dist matrix
  D_spad <- cbind(D, pad)
  
  D_latent_upad <- rbind(t(pad), D_latent) # padding above dist matrix 
  D_upad <- rbind(t(pad), D)
  
  latent_pad <- rbind(latent, pad2) # padding below latent variables
  latent_upad <- rbind(pad2, latent) # padding above latent variables 

  grad_sll <- matrix(NA, nrow = n, ncol = dims)
  
  for (i in 1:n){
    step3 <- matrix(0, nrow = 2 * band.no, ncol = dims)
    #step3.a <- matrix(0, nrow = band.no, ncol = dims)
    #step3.b <- matrix(0, nrow = band.no, ncol = dims)
    for (j in 1:band.no){
      
      # accounting for couplings to the right of d_ii
      stat1 <- (D_latent_spad[i, i + j]) / sqrt(sigma) 
      step1.a <- (D_latent_spad[i, i + j] - D_spad[i, i + j]) / sigma 
      step2.a <- dnorm(stat1) / (sqrt(sigma) * pnorm(stat1))
      step3[j, ] <- (step1.a + step2.a) * 
        ((latent_pad[i, ] - latent_pad[i + j, ]) / D_latent_spad[i, i + j])
      
      # accounting for couplings above d_ii
      stat2 <- D_latent_upad[i + band.no - j, i] / sqrt(sigma)
      step1.b <- (D_latent_upad[i + band.no - j, i] - D_upad[i + band.no - j, i]) / sigma
      step2.b <- dnorm(stat2) / (sqrt(sigma) * pnorm(stat2))
      step3[j + band.no, ] <- (step1.b + step2.b) * 
        ((latent_pad[i, ] - latent_upad[i + band.no - j, ]) / D_latent_upad[i + band.no - j, i])
    }
    
    # combine both types of couplings 
    #step3 <- rbind(step3.a, step3.b)
    grad_sll[i, ] <- - colSums(step3, na.rm = TRUE) - latent_pad[i, ]
  }
  return(grad_sll)
}
```

### Simulation 

```{r}
set.seed(12345)
samp.size <- 200
Z_ex <- mvrnorm(samp.size, mu = c(0,0), Sigma = diag(c(1, 1)))
#Z_tilde <- mvrnorm(25, mu = c(0,0), Sigma = diag(c(1, 1))) + 0.1
D_ex <- as.matrix(dist(Z_ex, diag = TRUE, upper = TRUE))

ll_time <- c()
for (i in 1:samp.size){
  stime <- proc.time()
  sll_results <- s_bmds_ll2(sigma = 0.3, D = D_ex, latent = Z_ex, band.no = i)
  endtime <- proc.time() - stime
  ll_time[i] <- endtime[3]
}

#ll_time
#s_bmds_ll2(sigma = 0.3, D_ex, latent = Z_tilde, band.no = 15)

grad_time <- c()
for (i in 1:samp.size){
  stime <- proc.time()
  sgrad_results <- s_grad(sigma = 0.3, D_ex, latent = Z_ex, band.no = i)
  endtime <- proc.time() - stime
  grad_time[i] <- endtime[3]
}

#grad_time
```

### Plots

```{r}
raw_data <- tibble(bands = seq(1, samp.size), ll_time, grad_time) 

ggplot(raw_data, aes(bands, ll_time)) + geom_point() +
  labs(title = "Raw Likelihood", 
       x = "Number of Bands", y = "Elapsed Time (sec)")

ggplot(raw_data, aes(bands, grad_time)) + geom_point() +
  labs(title = "Raw Gradient", 
       x = "Number of Bands", y = "Elapsed Time (sec)")

## combined graph 

raw_data2 <- raw_data %>% gather(., key = "raw type", value = "elapsed time", c(ll_time, grad_time))

ggplot(raw_data2, aes(bands, `elapsed time`, color = `raw type`)) + 
  geom_point() +
  geom_smooth(aes(color = `raw type`), method = "loess") + 
  labs(title = paste0("Raw Likelihood & Gradient Evaluations \n (N = ", samp.size, ")"), 
       x = "Number of Bands", y = "Elapsed Time (sec)",
       color = "") +
  theme_minimal() + 
  #scale_color_discrete(labels = c("gradient", "likelihood")) +
  scale_color_manual(values = c("blue", "orange"),
                     labels = c("gradient", "likelihood"))
  
```

