---
title: "Computational_evals"
author: "Ami Sheth"
date: "2023-01-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import libraries
```{r}
library(tidyverse)
library(invgamma)
library(mvtnorm)
library(truncnorm)
library(gridExtra)
```

Source the necessary functions

```{r}
#setwd("~/sparseBMDS/code")
source("sBMDS_functions.R")
```

```{r}
# s_target3 <- function(theta, sigma, band.no, D) { # theta the latent variable; dims x 1 vector
#   output <- s_bmds_ll(sigma, D, latent = theta, band.no) + 
#     sum(mvtnorm::dmvnorm(theta, log = TRUE)) # independent, standard Gaussian prior for theta
#   return(output)
# }
# 
# delta <- function(n) {
#   return( min(0.01, n^(-0.5)) )
# }
# 
# s_adapt_metropolis3 <- function(dims, maxIts, D, sigma,
#                               targetAccept = 0.8, 
#                               stepSize = 1, band.no) {
#   
#   # create the chain 
#   n <- dim(D)[1]
#   chain <- array(0, dim = c(maxIts, n, dims))
#   
#   # specify the first random value
#   chain[1, , ] <- mvtnorm::rmvnorm(n, mean = rep(0, dims), sigma = diag(dims))
#   
#   totalAccept <- rep(0, maxIts)
#   Acceptances = 0 # total acceptances within adaptation run (<= SampBound)
#   SampBound = 50   # current total samples before adapting radius
#   SampCount = 0   # number of samples collected (adapt when = SampBound)
#   
#   for (s in 2:maxIts) {
#     
#     thetaStar <- cbind(rnorm(n, mean = chain[s - 1, , 1], sd = stepSize), 
#                        rnorm(n, mean = chain[s - 1, , 2], sd = stepSize))
#     # smaller proposal variance = more acceptances 
#     # proposal: normal dist
#     u <- runif(1)
#     # Metropolis, A = target(thetaStar)/target(previous iteration)
#     logA <- s_target3(thetaStar, sigma, band.no, D) - 
#       s_target3(chain[s - 1, , ], sigma, band.no, D) # target on log scale
#     
#     if(log(u) < logA) {
#       chain[s, , ] <- thetaStar # ACCEPT !! # next iteration to thetastar
#       totalAccept[s] <- 1
#       Acceptances = Acceptances + 1 # acceptance counter
#     } else {
#       chain[s, , ] <- chain[s - 1, , ] # REJECT !! # next iteration stays at same iteration
#     }
#     
#     SampCount <- SampCount + 1
#     
#     # tune
#     if (SampCount == SampBound) { 
#       AcceptRatio <- Acceptances / SampBound
#       if (AcceptRatio > targetAccept) {
#         stepSize <- stepSize * (1 + delta(s - 1)) # increase stepsize 
#       } else {
#         stepSize <- stepSize * (1 - delta(s - 1)) # decrease stepsize
#       }
#       
#       # reset Sampcount and Acceptances
#       SampCount <- 0
#       Acceptances <- 0
#     }
#     
#     if (s %% 100 == 0) cat("Iteration ", s, "\n","stepSize: ", stepSize, "\n") 
#   }
#   
#   cat("Acceptance rate: ", sum(totalAccept)/(maxIts - 1))
#   
#   return(chain)
# }
```

```{r}
# set.seed(12345)
# Z.test <- mvtnorm::rmvnorm(25, mean = rep(0, 2), sigma = diag(c(1, 1))) # dims = 2, n = 25
# D.test <- as.matrix(dist(Z.test, diag = TRUE, upper = TRUE)) # n x n matrix of distances
# noise.test <- matrix(rtruncnorm(25^2, mean = 0, sd = sqrt(.3)), 25, 25) 
# noise.test <- (noise.test + t(noise.test)) / 2
# diag(noise.test) <- 0
# Dnoise.test <- noise.test + D.test
# test.results <- s_adapt_metropolis3(dims = 2, maxIts = 100000, D = Dnoise.test,
#                                     sigma = 0.3, targetAccept = 0.65, stepSize = 1,
#                                     band.no = 10)
# 
# test.results2 <- s_adapt_metropolis2(dims = 2, maxIts = 100000, band.no = 25, targetAccept = 0.65,
#                                      targetAccept_Sigma = 0.5, D = Dnoise.test, 
#                                      stepSize = 1, stepSizeSigma = 1)
# 
# test.dist <- array(0, dim = c(100000, 25, 25))
# for (i in 1:100000){
#   test.dist[i, , ] <- as.matrix(dist(test.results[i, , ], diag = TRUE, upper = TRUE))
# }
# 
# test.dist2 <- array(0, dim = c(100000, 25, 25))
# for (i in 1:100000){
#   test.dist2[i, , ] <- as.matrix(dist(test.results2[[2]][i, , ], diag = TRUE, upper = TRUE))
# }
# 
# plot(test.dist[-(1:30000), 1, 2], type = "l")
# abline(h = Dnoise.test[1, 2], col = "red")
# abline(h = D.test[1, 2], col = "blue")
# plot(test.dist2[-(1:30000), 1, 2], type = "l")
# abline(h = D.test[1, 2], col = "red")
```

Simulate data (5x5 grid)

```{r}
set.seed(12345)

l <- rep(c("blue", "green", "yellow", "orange", "red"), 5)

data_test <- tibble(x = rep(seq(-1, 1, by = .5), 5),
                    y = c(rep(-1, 5), rep(-.5, 5), rep(0, 5), rep(.5, 5), rep(1, 5)),
                    color = l)
dist_test <- as.matrix(dist(data_test[, 1:2], diag = TRUE, upper = TRUE))

# permuting items of the data
data_test2 <- data_test[sample(nrow(data_test)), ]
dist_test2 <- as.matrix(dist(data_test2[, 1:2], diag = TRUE, upper = TRUE))

# both datasets are the same
ggplot(data = data_test, aes(x, y, color = color)) +
  geom_point() + theme(legend.position = "none")

ggplot(data = data_test2, aes(x, y, color = color)) +
  geom_point() + theme(legend.position = "none")

# noise <- matrix(rtruncnorm(25^2, mean = 0, sd = .5), 25, 25)
# noise <- (noise + t(noise)) / 2
# diag(noise) <- 0
# D.noise <- noise + dist_test2
# sim <- s_adapt_metropolis(dims = 2, maxIts = 100000, targetAccept = 0.65, 
#                           D = D.noise, sigma = .5^2, 
#                           stepSize = 1, band.no = 25)
```

# elbow graphs for MSE

```{r}
set.seed(12345)
#n <- 25
mse_count <- matrix(0, nrow = 100000, ncol = 25)
burnin <- 30000
#Z.sim <- mvtnorm::rmvnorm(n, mean = rep(0, 2), sigma = diag(c(1, 1))) # dims = 2, n = 25
#D.sim <- as.matrix(dist(Z.sim, diag = TRUE, upper = TRUE)) # n x n matrix of distances
noise <- matrix(rtruncnorm(25^2, mean = 0, sd = .005), 25, 25) 
noise <- (noise + t(noise)) / 2
diag(noise) <- 0
D.noise <- noise + dist_test2
for (s in 1:25){
  sim <- sbmds_metropolis_fast(dims = 2, maxIts = 100000, D = D.noise, 
                               sigmasq = .005^2, band.no = s, 
                               targetAccept = 0.65, stepSize = 1)
  #error <- c()
  for (t in 1:100000){
    mse_count[t, s] <- mean((as.matrix(dist(sim[t, , ], diag = TRUE, upper = TRUE)) - dist_test2)^2)
  }
  #mse_count[s] <- mean(error[-(1:burnin)])
}
```
```{r}
plot(colSums(mse_count[70000:100000, ]), main = "sd = .005",
     xlab = "Number of Bands", ylab = "MSE")
```

# mse with se lines

```{r}
#set.seed(12345)
n <- 25
burnin <- 30000
B <- 10

mse_grid <- matrix(0, nrow = B, ncol = n)
for (b in 1:B){
  noise <- matrix(rtruncnorm(n^2, mean = 0, sd = .001), n, n) 
  noise <- (noise + t(noise)) / 2
  diag(noise) <- 0
  D.noise <- noise + dist_test2
  for (s in 1:n){
    sim <- sbmds_metropolis_fast(dims = 2, maxIts = 100000, D = D.noise, 
                               sigmasq = .001^2, band.no = s, 
                               targetAccept = 0.65, stepSize = 1)
    error <- c()
    for (t in 1:100000){
      error[t] <- mean((as.matrix(dist(sim[t, , ], diag = TRUE, upper = TRUE)) - dist_test2)^2)
    }
    mse_grid[b, s] <- mean(error[-(1:burnin)])
  }
}
```

```{r}
mse_grid2 <- mse_grid
colnames(mse_grid2) <- seq(1, 25)#paste("band", seq(1, 25))
t.msegrid <- as_tibble(mse_grid2)

mse.plot.data <- gather(data = t.msegrid, key = "band #", value = "mse value", 
                        c(1:25)) %>%
  group_by(., `band #`) %>% 
  summarise(mmse = mean(`mse value`), 
            sdmse = sd(`mse value`),
            lqmse = quantile(`mse value`, .025), 
            uqmse = quantile(`mse value`, .975)) %>% 
  mutate(`band #` = as.integer(`band #`))

# 95% confidence interval  
mse.plot.data %>% 
  ggplot(aes(`band #`, mmse, ymin = mmse - 1.96 * sdmse, ymax = mmse + 1.96 * sdmse)) + 
  geom_pointrange() + 
  labs(title = "95% Confidence Interval for MSE when SD = 0.001",
       x = "Number of Bands", y = "Mean Squared Error")

# 95% credible interval 
mse.plot.data %>% 
  ggplot(aes(`band #`, mmse, ymin = lqmse, ymax = uqmse)) + 
  geom_pointrange(size = .1) + 
  labs(title = "95% Credible Interval for MSE when SD = 0.001",
       x = "Number of Bands", y = "Mean Squared Error")

```

# std error graphs 

```{r}
sim_adderror <- function(sd, dims, size, maxIts, band.no, targetAccept, data,
                         stepSize, burnin){
  data_sim <- array(0, dim = c(length(sd), size, dims))
  ees <- c()
  for (i in 1:length(sd)){
    noise <- matrix(rtruncnorm(size^2, mean = 0, sd = sd[i]), size, size)
    noise <- (noise + t(noise)) / 2
    diag(noise) <- 0
    D.noise <- noise + data
    sim <- sbmds_metropolis_fast(dims, maxIts, D = D.noise, 
                               sigmasq = sd[i]^2, band.no, 
                               targetAccept, stepSize)
    
    # calculate a distance matrix
    dist_mat_mh <- array(0, dim = c(maxIts, size, size))

    for (j in 1:maxIts){
      dist_mat_mh[j, , ] <- as.matrix(dist(sim[j, , ],
                                           diag = TRUE, upper = TRUE))
    }
  
    ees[i] <- sum(coda::effectiveSize(dist_mat_mh[-(1:burnin), , 10]))
    # look at minimum across all the (n 2) pairwise distances, > 100
    
    if (ees[i] > 4000){
      data_sim[i, , ] <- colMeans(sim[-(1:burnin), , ])
    }
    # data_sim[i, , ] <- sim[maxIts, , ]
  }
  return(list(sim, dist_mat_mh))
}

# procrustes <- function(A, B){
#   # center and normalize A 
#   A.centered <- t(scale(t(A), center = TRUE, scale = FALSE))
#   A.size <- norm(A.centered, type = "F") / (ncol(A) * nrow(A))
#   A.normalized <- A.centered / A.size
# 
#   # center and normalize B
#   B.centered <- t(scale(t(B), center = TRUE, scale = FALSE))
#   B.size <- norm(B.centered, type = "F") / (ncol(B) * nrow(B))
#   B.normalized <- B.centered / B.size
# 
#   # Rotation matrix T 
#   svd.results <- svd(B.normalized %*% t(A.normalized))
#   U <- svd.results$u
#   V <- svd.results$v
#   T <- V %*% t(U)
# 
#   # B transformed
#   B.transformed <- T %*% B.normalized
# 
#   # Error after superimposition
#   RSS <- norm(A.normalized - B.transformed,  type = "F")
# 
#   # Return
#   return(list(A.normalized = A.normalized, B.normalized = B.normalized, rotation.mtx = T, B.transformed = B.transformed, RSS = RSS))
# }
```

```{r}
set.seed(500)
sd_opt <- c(.001, 0.05, 0.1, .5) #c(0.005, 0.05, 0.25, .5) #c(0.001, 0.01, .1, 1)
#0.004, 0.02, 0.1, 0.5
add_band25 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                           maxIts = 100000, band.no = 25,
                           targetAccept = 0.65, data = dist_test2,
                           stepSize = 1, burnin = 30000)
# acceptance rate  for sd = .001 is ~.12
# acceptance rate  for sd = .05 is ~.42
# acceptance rate  for sd = .1 is ~.46
# acceptance rate  for sd = .5 is ~.54
```
```{r}
set.seed(500)
add_band15 <- sim_adderror(sd = sd_opt, dims = 2, size = 25, 
                           maxIts = 100000, band.no = 15, 
                           targetAccept = 0.65, data = dist_test2,
                           stepSize = 1, burnin = 30000)
```

```{r}
set.seed(500)
add_band10 <- sim_adderror(sd = sd_opt, dims = 2, size = 25, 
                           maxIts = 100000, band.no = 10, 
                           targetAccept = 0.65, data = dist_test2,
                           stepSize = 1, burnin = 30000)
# acceptance rate  for sd = .001 is ~.14
# acceptance rate  for sd = .05 is ~.43
# acceptance rate  for sd = .1 is ~.47
# acceptance rate  for sd = .5 is ~.54
```
```{r}
set.seed(500)
add_band8 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                          maxIts = 100000, band.no = 8,
                          targetAccept = 0.65, data = dist_test2,
                          stepSize = 1, burnin = 30000)
```
```{r}
set.seed(500)
add_band7 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                          maxIts = 100000, band.no = 7,
                          targetAccept = 0.65, data = dist_test2,
                          stepSize = 1, burnin = 30000)
```

```{r}
set.seed(500)
add_band6 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                          maxIts = 200000, band.no = 6,
                          targetAccept = 0.65, data = dist_test2,
                          stepSize = 1, burnin = 150000)
```

```{r}
set.seed(500)
sd_opt <- c(0.5)
add_band5 <- sim_adderror(sd = sd_opt, dims = 2, size = 25, 
                          maxIts = 100000, band.no = 5,
                          targetAccept = 0.238, data = dist_test2,
                          stepSize = 1, burnin = 30000)
# run long enough to get effsamp = 100
```

```{r}
set.seed(500)
#sd_opt <- c(0.005)
add_band4 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                          maxIts = 200000, band.no = 4,
                          targetAccept = 0.65, data = dist_test2,
                          stepSize = 1, burnin = 100000)
```

```{r}
theme_update(plot.title = element_text(hjust = 0.5, size = rel(.75)),
             legend.position = "none")

# 25 bands 
g1.25.add <- ggplot(data = tibble(x.sim = add_band25[[1]][1, , 1], y.sim = add_band25[[1]][1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("25 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
  #coord_fixed(ratio = 1, xlim = c(-1.5, 2), ylim = c(-1.5, 1.5))

g2.25.add <- ggplot(data = tibble(x.sim = add_band25[[1]][2, , 1], y.sim = add_band25[[1]][2, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("25 bands \n sd = ", sd_opt[2]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# coord_fixed(ratio = 1, xlim = c(-1.5, 1.5), ylim = c(-1.75, 1.5))

g3.25.add <- ggplot(data = tibble(x.sim = add_band25[[1]][3, , 1], y.sim = add_band25[[1]][3, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("25 bands \n sd = ", sd_opt[3]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.25.add <- ggplot(data = tibble(x.sim = add_band25[[1]][4, , 1], y.sim = add_band25[[1]][4, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("25 bands \n sd = ", sd_opt[4]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 15 bands
g1.15.add <- ggplot(data = tibble(x.sim = add_band15[[1]][1, , 1], y.sim = add_band15[[1]][1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("15 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-1, 3), ylim = c(-1, 3))
  #coord_fixed(ratio = 1, xlim = c(-1.5, 2), ylim = c(-1.5, 1.5))

g2.15.add <- ggplot(data = tibble(x.sim = add_band15[[1]][2, , 1], y.sim = add_band15[[1]][2, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("15 bands \n sd = ", sd_opt[2]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(0, 4), ylim = c(-2, 2))
# coord_fixed(ratio = 1, xlim = c(-1.5, 1.5), ylim = c(-1.75, 1.5))

g3.15.add <- ggplot(data = tibble(x.sim = add_band15[[1]][3, , 1], y.sim = add_band15[[1]][3, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("15 bands \n sd = ", sd_opt[3]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.15.add <- ggplot(data = tibble(x.sim = add_band15[[1]][4, , 1], y.sim = add_band15[[1]][4, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("15 bands \n sd = ", sd_opt[4]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))


# 10 bands
g1.10.add <- ggplot(data = tibble(x.sim = add_band10[[1]][1, , 1], y.sim = add_band10[[1]][1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("10 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-1, 3), ylim = c(-1, 3))
  #coord_fixed(ratio = 1, xlim = c(-1.5, 2), ylim = c(-1.5, 1.5))

g2.10.add <- ggplot(data = tibble(x.sim = add_band10[[1]][2, , 1], y.sim = add_band10[[1]][2, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("10 bands \n sd = ", sd_opt[2]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# coord_fixed(ratio = 1, xlim = c(-1.5, 1.5), ylim = c(-1.75, 1.5))

g3.10.add <- ggplot(data = tibble(x.sim = add_band10[[1]][3, , 1], y.sim = add_band10[[1]][3, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("10 bands \n sd = ", sd_opt[3]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.10.add <- ggplot(data = tibble(x.sim = add_band10[[1]][4, , 1], y.sim = add_band10[[1]][4, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("10 bands \n sd = ", sd_opt[4]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 8 bands

g1.8.add <- ggplot(data = tibble(x.sim = add_band8[[1]][1, , 1], y.sim = add_band8[[1]][1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("8 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-1, 3), ylim = c(-3, 1))
  #coord_fixed(ratio = 1, xlim = c(-1.5, 2), ylim = c(-1.5, 1.5))

g2.8.add <- ggplot(data = tibble(x.sim = add_band8[[1]][2, , 1], y.sim = add_band8[[1]][2, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("8 bands \n sd = ", sd_opt[2]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-1, 3))
# coord_fixed(ratio = 1, xlim = c(-1.5, 1.5), ylim = c(-1.75, 1.5))

g3.8.add <- ggplot(data = tibble(x.sim = add_band8[[1]][3, , 1], y.sim = add_band8[[1]][3, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("8 bands \n sd = ", sd_opt[3]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.8.add <- ggplot(data = tibble(x.sim = add_band8[[1]][4, , 1], y.sim = add_band8[[1]][4, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("8 bands \n sd = ", sd_opt[4]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 7 bands

g1.7.add <- ggplot(data = tibble(x.sim = add_band7[[1]][1, , 1], y.sim = add_band7[[1]][1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("7 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
  #coord_fixed(ratio = 1, xlim = c(-1.5, 2), ylim = c(-1.5, 1.5))

g2.7.add <- ggplot(data = tibble(x.sim = add_band7[[1]][2, , 1], y.sim = add_band7[[1]][2, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("7 bands \n sd = ", sd_opt[2]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# coord_fixed(ratio = 1, xlim = c(-1.5, 1.5), ylim = c(-1.75, 1.5))

g3.7.add <- ggplot(data = tibble(x.sim = add_band7[[1]][3, , 1], y.sim = add_band7[[1]][3, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("7 bands \n sd = ", sd_opt[3]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.7.add <- ggplot(data = tibble(x.sim = add_band7[[1]][4, , 1], y.sim = add_band7[[1]][4, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("7 bands \n sd = ", sd_opt[4]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 6 bands

g1.6.add <- ggplot(data = tibble(x.sim = add_band6[[1]][1, , 1], y.sim = add_band6[[1]][1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("6 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
  #coord_fixed(ratio = 1, xlim = c(-1.5, 2), ylim = c(-1.5, 1.5))

g2.6.add <- ggplot(data = tibble(x.sim = add_band6[[1]][2, , 1], y.sim = add_band6[[1]][2, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("6 bands \n sd = ", sd_opt[2]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# coord_fixed(ratio = 1, xlim = c(-1.5, 1.5), ylim = c(-1.75, 1.5))

g3.6.add <- ggplot(data = tibble(x.sim = add_band6[[1]][3, , 1], y.sim = add_band6[[1]][3, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("6 bands \n sd = ", sd_opt[3]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.6.add <- ggplot(data = tibble(x.sim = add_band6[[1]][4, , 1], y.sim = add_band6[[1]][4, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("6 bands \n sd = ", sd_opt[4]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 5 bands

g1.5.add <- ggplot(data = tibble(x.sim = add_band5[[1]][1, , 1], y.sim = add_band5[[1]][1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("5 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-3, 1))
  #coord_fixed(ratio = 1, xlim = c(-1.5, 2), ylim = c(-1.5, 1.5))

g2.5.add <- ggplot(data = tibble(x.sim = add_band5[[1]][2, , 1], y.sim = add_band5[[1]][2, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("5 bands \n sd = ", sd_opt[2]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# coord_fixed(ratio = 1, xlim = c(-1.5, 1.5), ylim = c(-1.75, 1.5))

g3.5.add <- ggplot(data = tibble(x.sim = add_band5[[1]][3, , 1], y.sim = add_band5[[1]][3, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("5 bands \n sd = ", sd_opt[3]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.5.add <- ggplot(data = tibble(x.sim = add_band5[[1]][4, , 1], y.sim = add_band5[[1]][4, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("5 bands \n sd = ", sd_opt[4]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 4 bands 

g1.4.add <- ggplot(data = tibble(x.sim = add_band4[[1]][1, , 1], y.sim = add_band4[[1]][1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("4 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
  #coord_fixed(ratio = 1, xlim = c(-1.5, 2), ylim = c(-1.5, 1.5))

g2.4.add <- ggplot(data = tibble(x.sim = add_band4[[1]][2, , 1], y.sim = add_band4[[1]][2, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("4 bands \n sd = ", sd_opt[2]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# coord_fixed(ratio = 1, xlim = c(-1.5, 1.5), ylim = c(-1.75, 1.5))

g3.4.add <- ggplot(data = tibble(x.sim = add_band4[[1]][3, , 1], y.sim = add_band4[[1]][3, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("4 bands \n sd = ", sd_opt[3]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.4.add <- ggplot(data = tibble(x.sim = add_band4[[1]][4, , 1], y.sim = add_band4[[1]][4, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = paste("4 bands \n sd = ", sd_opt[4]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

grid.arrange(g1.25.add, g2.25.add, g3.25.add, g4.25.add, 
          g1.15.add, g2.15.add, g3.15.add, g4.15.add,
          ncol = 4)
grid.arrange(g1.10.add, g2.10.add, g3.10.add, g4.10.add, 
             g1.5.add, g2.5.add, g3.5.add, g4.5.add, 
             ncol = 4)

# grid.arrange(g1.8.add, g2.8.add, g3.8.add, g4.8.add, 
#           g1.5.add, g2.5.add, g3.5.add, g4.5.add, ncol = 4)

# grid.arrange(g1.7.add, g2.7.add, g3.7.add, g4.7.add,
#           g1.4.add, g2.4.add, g3.4.add, g4.4.add, ncol = 4)
```

Additional sd error exploration

```{r}
set.seed(12345)
sd_opt <- c(0.4) #c(0.001, 0.01, .1, 1)
test_band25 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                           maxIts = 100000, band.no = 25,
                           targetAccept = 0.65, data = dist_test2,
                           stepSize = 1, burnin = 30000)
test_band10 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                           maxIts = 100000, band.no = 10,
                           targetAccept = 0.65, data = dist_test2,
                           stepSize = 1, burnin = 30000)
test_band8 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                           maxIts = 100000, band.no = 8,
                           targetAccept = 0.65, data = dist_test2,
                           stepSize = 1, burnin = 30000)
test_band5 <- sim_adderror(sd = sd_opt, dims = 2, size = 25,
                           maxIts = 100000, band.no = 5,
                           targetAccept = 0.65, data = dist_test2,
                           stepSize = 1, burnin = 30000)

ggplot(data = tibble(x.sim = test_band8[1, , 1], y.sim = test_band8[1, , 2],
                              color = data_test2$color)) + 
  geom_point(aes(x.sim, y.sim, color = color)) + 
  labs(title = sd_opt[1], #title = paste("10 bands \n sd = ", sd_opt[1]),
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
```

```{r}
# grid_data <- read_csv("txt_simdata/error_grid_results.txt", 
#                       col_names = c("SD", "BAND", "ESS", "X", "Y", "color"))

grid_data <- read_csv("Users/amisheth/sparseBMDS/code/txt_simdata/error_grid_results.txt", col_names = c("SD", "BAND", "ESS", "X", "Y", "color"))

grid_data %>% filter(ESS < 100)
  #filter(SD == .5 & BAND == 25)
```

```{r}
theme_update(plot.title = element_text(hjust = 0.5, size = rel(.75)),
             legend.position = "none")

# 25 bands
g1.25.add <- grid_data %>% filter(SD == .1 & BAND == 25) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "25 bands \n sd = .1",
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g2.25.add <- grid_data %>% filter(SD == .25 & BAND == 25) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "25 bands \n sd = .25",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g3.25.add <- grid_data %>% filter(SD == .4 & BAND == 25) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "25 bands \n sd = .4",
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.25.add <- grid_data %>% filter(SD == .55 & BAND == 25) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "25 bands \n sd = .55",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 15 bands
g1.15.add <- grid_data %>% filter(SD == .1 & BAND == 15) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "15 bands \n sd = .1",
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g2.15.add <- grid_data %>% filter(SD == .25 & BAND == 15) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "15 bands \n sd = .25",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g3.15.add <- grid_data %>% filter(SD == .4 & BAND == 15) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "15 bands \n sd = .4",
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.15.add <- grid_data %>% filter(SD == .55 & BAND == 15) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "15 bands \n sd = .55",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 10 bands
g1.10.add <- grid_data %>% filter(SD == .1 & BAND == 10) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "10 bands \n sd = .1",
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g2.10.add <- grid_data %>% filter(SD == .25 & BAND == 10) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "10 bands \n sd = .25",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g3.10.add <- grid_data %>% filter(SD == .4 & BAND == 10) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "10 bands \n sd = .4",
         x = "",
         y = "") + 
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.10.add <- grid_data %>% filter(SD == .55 & BAND == 10) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "10 bands \n sd = .55",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 5 bands
g1.5.add <- grid_data %>% filter(SD == .1 & BAND == 5) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "5 bands \n sd = .1",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g2.5.add <- grid_data %>% filter(SD == .25 & BAND == 5) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "5 bands \n sd = .25",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g3.5.add <- grid_data %>% filter(SD == .4 & BAND == 5) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "5 bands \n sd = .4",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g4.5.add <- grid_data %>% filter(SD == .55 & BAND == 5) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "5 bands \n sd = .55",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

# 3 bands
# g1.3.add <- grid_data %>% filter(SD == .004 & BAND == 3) %>% 
#   ggplot(data = .) + 
#   geom_point(aes(X, Y, color = color)) +
#   labs(title = "3 bands \n sd = .004",
#          x = "",
#          y = "") +
#   coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# 
# g2.3.add <- grid_data %>% filter(SD == .02 & BAND == 3) %>% 
#   ggplot(data = .) + 
#   geom_point(aes(X, Y, color = color)) +
#   labs(title = "3 bands \n sd = .02",
#          x = "",
#          y = "") +
#   coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# 
# g3.3.add <- grid_data %>% filter(SD == .1 & BAND == 3) %>% 
#   ggplot(data = .) + 
#   geom_point(aes(X, Y, color = color)) +
#   labs(title = "3 bands \n sd = .1",
#          x = "",
#          y = "") +
#   coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))
# 
# g4.3.add <- grid_data %>% filter(SD == .5 & BAND == 3) %>% 
#   ggplot(data = .) + 
#   geom_point(aes(X, Y, color = color)) +
#   labs(title = "3 bands \n sd = .5",
#          x = "",
#          y = "") +
#   coord_fixed(ratio = 1, xlim = c(-1, 1), ylim = c(-1, 1))

grid.arrange(g1.25.add, g2.25.add, g3.25.add, g4.25.add,
          g1.15.add, g2.15.add, g3.15.add, g4.15.add,
          ncol = 4)
grid.arrange(g1.10.add, g2.10.add, g3.10.add, g4.10.add, 
             g1.5.add, g2.5.add, g3.5.add, g4.5.add, 
             ncol = 4)
# grid.arrange(g1.3.add, g2.3.add, g3.3.add, g4.3.add, 
#              ncol = 4)
```


```{r}
grid_data_hmc <- read_csv("/Users/amisheth/sparseBMDS/code/txt_simdata/error_grid_hmc_results.txt", col_names = c("SD", "BAND", "ESS", "X", "Y", "color"))
grid_data_hmc
```
```{r}
# 10 bands
g1.10.hmc <- grid_data_hmc %>% filter(SD == .004 & BAND == 10) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "10 bands \n sd = .004",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g2.10.hmc <- grid_data_hmc %>% filter(SD == .02 & BAND == 10) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "10 bands \n sd = .02",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g3.10.hmc <- grid_data_hmc %>% filter(SD == .1 & BAND == 10) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "10 bands \n sd = .1",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-1, 1), ylim = c(-1, 1))

g4.10.hmc <- grid_data_hmc %>% filter(SD == .5 & BAND == 10) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "10 bands \n sd = .5",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-1, 1), ylim = c(-1, 1))

# 5 bands
g1.5.hmc <- grid_data_hmc %>% filter(SD == .004 & BAND == 5) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "5 bands \n sd = .004",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g2.5.hmc <- grid_data_hmc %>% filter(SD == .02 & BAND == 5) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "5 bands \n sd = .02",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-2, 2), ylim = c(-2, 2))

g3.5.hmc <- grid_data_hmc %>% filter(SD == .1 & BAND == 5) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "5 bands \n sd = .1",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-1, 1), ylim = c(-1, 1))

g4.5.hmc <- grid_data_hmc %>% filter(SD == .5 & BAND == 5) %>% 
  ggplot(data = .) + 
  geom_point(aes(X, Y, color = color)) +
  labs(title = "5 bands \n sd = .5",
         x = "",
         y = "") +
  coord_fixed(ratio = 1, xlim = c(-1, 1), ylim = c(-1, 1))

grid.arrange(g1.10.hmc, g2.10.hmc, g3.10.hmc, g4.10.hmc,
             g1.5.hmc, g2.5.hmc, g3.5.hmc, g4.5.hmc, 
             ncol = 4)
```

