---
title: "sBMDS Computational Efficiency"
author: "Ami Sheth"
date: "2023-03-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import libraries 
```{r}
library(MassiveMDS)
library(mvtnorm)
library(truncnorm)
library(plyr)
library(tidyverse)
library(ggpubr)
```
## Results from node - graph & tables, all miness > 100

```{r}
comptime_data <- read_csv("~/sparseBMDS/code/data_graphs/ess_time.txt",
                          col_names = c("item", "method", "LM", "time", 
                                        "miness", "medess"))
View(comptime_data)
```
```{r}
pal <- c("darkred", "orangered2", "darkgoldenrod1", "lightgoldenrod", 
         "darkcyan", "navyblue")

ct_min <- comptime_data %>%
  mutate(type = paste(method, LM)) %>% 
  filter(type %in% c("FHMC FALSE", "FMH FALSE", "SMH FALSE", "SMH TRUE", 
                     "SSHMC FALSE", "SSHMC TRUE")) %>% 
  ggplot(aes(x = factor(item), y = log(miness / time * 3600), fill = type)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme(legend.position = "right") + 
  labs(#title = "Computational Performance", 
       y = "Log minimum ESS per hour", x = "Number of data points") +
  scale_fill_manual(values = pal, name = "Method",
                    labels = c("Full/HMC", "Full/MH", "B-sBMDS/MH", "L-sBMDS/MH", 
                               "B-sBMDS/HMC", "L-sBMDS/HMC")) + 
  theme_bw()
```
```{r}
ggsave("compperf.miness.png", ct_min, path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3)
```

```{r}
theme_set(theme_bw())
# pal <- c("FHMC" = "orangered2", "FMH" = "darkgoldenrod1", 
#          "SMH" = "darkcyan", "SSHMC" = "navyblue")

pal <- c("darkred", "orangered2", "darkgoldenrod1", "lightgoldenrod", 
         "darkcyan", "navyblue")

ct1 <- comptime_data %>% #filter(LM == FALSE) %>% 
  ggplot(aes(x = factor(item), y = log(miness / time * 3600), fill = method)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme(legend.position = "right") + 
  labs(title = "Bands", y = NULL, x = NULL) + 
  scale_fill_manual(values = pal, name = "Method", 
                    labels = c("F/HMC", "F/MH", "S/MH", "S/HMC"))

ct2 <- comptime_data %>% filter(LM == TRUE) %>% 
  ggplot(aes(x = factor(item), y = log(miness / time * 3600), fill = method)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme(legend.position = "right") + 
  labs(title = "Landmarks", y = NULL, x = NULL) + 
  scale_fill_manual(values = pal, name = "Method")

ct_min <- ggarrange(ct1, ct2, nrow = 1, ncol = 2, common.legend = TRUE, 
                     legend = "right")
ct_min <- annotate_figure(ct_min, 
                           left = "Log minimum ESS per hour",
                           #top = "Computational Performance", 
                           bottom = "Number of data points")
ct_min
```
```{r}
ggsave("compperf.miness.png", ct_min, path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3)
```

```{r}
theme_set(theme_bw())
pal <- c("orangered2", "darkgoldenrod1", "darkcyan", "navyblue")

ct3 <- comptime_data %>% filter(LM == FALSE) %>% 
  ggplot(aes(x = factor(item), y = log(medess / time * 3600), fill = method)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme(legend.position = "right") + 
  labs(title = "Bands", y = NULL, x = NULL) + 
  scale_fill_manual(values = pal, name = "Method",
                    labels = c("F/HMC", "F/MH", "S/MH", "S/HMC"))

ct4 <- comptime_data %>% filter(LM == TRUE) %>% 
  ggplot(aes(x = factor(item), y = log(medess / time * 3600), fill = method)) + 
  geom_bar(stat = "identity", position = "dodge") +
  theme(legend.position = "right") + 
  labs(title = "Landmarks", y = NULL, x = NULL) + 
  scale_fill_manual(values = pal, name = "Method")

ct_med <- ggarrange(ct3, ct4, nrow = 1, ncol = 2, common.legend = TRUE, 
                     legend = "right")
ct_med <- annotate_figure(ct_med, 
                          left = "Log median ESS per second", 
                          #top = "Computational Performance", 
                          bottom = "Number of data points")
ct_med
```
```{r}
ggsave("compperf.medess.png", ct_med, path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3)
```

