# load libraries
```{r}
library(MassiveMDS)
library(mvtnorm)
library(truncnorm)
library(tidyverse)
```

### read data from node
```{r}
mse_LM <- read_csv("~/sparseBMDS/code/data_graphs/mse_LM.txt", 
                     col_names = c("SD", "ITEM", "NUM", "MSE", "RELSIG", 
                                   "AR", "ARS"), 
                     col_types = list("d", "c", "d", "d", "d", "d", "d"))
mse_BAND <- read_csv("~/sparseBMDS/code/data_graphs/mse_bands.txt", 
                     col_names = c("SD", "ITEM", "NUM", "MSE", "RELSIG",
                                   "AR", "ARS"), 
                     col_types = list("d", "c", "d", "d", "d", "d", "d"))
#head(mse_LM)

#mse_LM %>% filter(ITEM == 10000 & SD == .4) %>% arrange(LANDMARK)
#mse_BAND %>% filter(ITEM == 10000 & SD == .4) %>% arrange(BAND)
```

### mse for distances
```{r}
theme_set(theme_bw())
theme_update(axis.title.x = element_blank(), axis.title.y = element_blank())

pal <- c("orangered2", "darkgoldenrod1", "darkcyan") 
#wesanderson::wes_palette(name = "Darjeeling1", n = 4, type = "discrete")

LM.1 <- mse_LM %>% 
  filter(SD == .1 & ITEM < 10000) %>% 
  ggplot(aes(x = NUM, y = MSE, color = ITEM)) + 
  geom_point(size = 1.2) +
  geom_line() + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Number of \n data points") + 
  labs(title = expression(sigma["true"] == .1))

LM.2 <- mse_LM %>% 
  filter(SD == .2 & ITEM < 10000) %>% 
  ggplot(aes(x = NUM, y = MSE, color = ITEM)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Number of \n data points") +
  labs(title = expression(sigma["true"] == .2))

LM.3 <- mse_LM %>% 
  filter(SD == .3 & ITEM < 10000) %>% 
  ggplot(aes(x = NUM, y = MSE, color = ITEM)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Number of \n data points") +
  labs(title = expression(sigma["true"] == .3))

LM.4 <- mse_LM %>% 
  filter(SD == .4 & ITEM < 10000) %>% 
  ggplot(aes(x = NUM, y = MSE, color = ITEM)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Number of \n data points") +
  labs(title = expression(sigma["true"] == .4))
```
```{r}
LM_all <- ggpubr::ggarrange(LM.1, LM.2, LM.3, LM.4, nrow = 2, ncol = 2, 
                            common.legend = TRUE, legend = "right")
LM_all <- ggpubr::annotate_figure(LM_all, 
                                  top = "Accuracy with truncated normal noise", 
                                  left = "Mean of MSE across distances", 
                                  bottom = "Number of landmarks")
LM_all
ggsave("mse_LM.png", plot = LM_all, path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3.5)
```

```{r}
theme_set(theme_bw())
theme_update(axis.title.x = element_blank(), axis.title.y = element_blank())

BAND.1 <- mse_BAND %>% 
  filter(SD == .1 & ITEM < 10000) %>% 
  ggplot(aes(x = NUM, y = MSE, color = ITEM)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Number of \n data points") +
  labs(title = expression(sigma["true"] == .1))

BAND.2 <- mse_BAND %>% 
  filter(SD == .2 & ITEM < 10000) %>% 
  ggplot(aes(x = NUM, y = MSE, color = ITEM)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Number of \n data points") +
  labs(title = expression(sigma["true"] == .2))

BAND.3 <- mse_BAND %>% 
  filter(SD == .3 & ITEM < 10000) %>% 
  ggplot(aes(x = NUM, y = MSE, color = ITEM)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Number of \n data points") +
  labs(title = expression(sigma["true"] == .3))

BAND.4 <- mse_BAND %>% 
  filter(SD == .4 & ITEM < 10000) %>% 
  ggplot(aes(x = NUM, y = MSE, color = ITEM)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Number of \n data points") +
  labs(title = expression(sigma["true"] == .4))
```
```{r}
BAND_all <- ggpubr::ggarrange(BAND.1, BAND.2, BAND.3, BAND.4, nrow = 2, 
                              ncol = 2, common.legend = TRUE, legend = "right")
BAND_all <- ggpubr::annotate_figure(BAND_all, 
                                    top = "Accuracy with truncated normal noise", 
                                    left = "Mean of MSE across distances", 
                                    bottom = "Number of bands")
BAND_all
ggsave("mse_BAND.png", plot = BAND_all, path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3.5)
```

### mse on distances for n = 10,000
```{r}
theme_set(theme_bw())
theme_update(axis.title.x = element_blank(), axis.title.y = element_blank())
pal <- c("darkred", "navyblue")

MSE.1 <- mse_BAND %>% filter(ITEM == 10000 & SD == .1) %>% 
  mutate(METHOD = "BAND") %>% 
  bind_rows(., mse_LM %>% filter(ITEM == 10000 & SD == .1) %>% 
              mutate(METHOD = "LANDMARK")) %>% 
  ggplot(aes(x = NUM, y = MSE, color = METHOD)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Method", 
                     labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(sigma["true"] == .1))

MSE.2 <- mse_BAND %>% filter(ITEM == 10000 & SD == .2) %>% 
  mutate(METHOD = "BAND") %>% 
  bind_rows(., mse_LM %>% filter(ITEM == 10000 & SD == .2) %>% 
              mutate(METHOD = "LANDMARK")) %>% 
  ggplot(aes(x = NUM, y = MSE, color = METHOD)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Method",
                     labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(sigma["true"] == .2))

MSE.3 <- mse_BAND %>% filter(ITEM == 10000 & SD == .3) %>% 
  mutate(METHOD = "BAND") %>% 
  bind_rows(., mse_LM %>% filter(ITEM == 10000 & SD == .3) %>% 
              mutate(METHOD = "LANDMARK")) %>% 
  ggplot(aes(x = NUM, y = MSE, color = METHOD)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Method",
                     labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(sigma["true"] == .3))

MSE.4 <- mse_BAND %>% filter(ITEM == 10000 & SD == .4) %>% 
  mutate(METHOD = "BAND") %>% 
  bind_rows(., mse_LM %>% filter(ITEM == 10000 & SD == .4) %>% 
              mutate(METHOD = "LANDMARK")) %>% 
  ggplot(aes(x = NUM, y = MSE, color = METHOD)) + 
  geom_line() + 
  geom_point(size = 1.2) + 
  scale_y_continuous(breaks = seq(.4, 1.6, .4)) +
  scale_color_manual(values = pal, name = "Method",
                     labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(sigma["true"] == .4))
```
```{r}
MSE_all <- ggpubr::ggarrange(MSE.1, MSE.2, MSE.3, MSE.4, nrow = 2, 
                              ncol = 2, common.legend = TRUE, legend = "right")
MSE_all <- ggpubr::annotate_figure(MSE_all, 
                                   top = "Accuracy with truncated normal noise",
                                   bottom = "Number of bands (landmarks)",
                                   left = "Mean of MSE across distances")
MSE_all
#MSE for n = 10,000
ggsave("mse_n10000.png", plot = MSE_all, path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3.5)
```


### median sigma 
```{r}
pal <- c("orangered2", "darkgoldenrod1", "darkcyan", "navyblue") 
sLM.1 <- mse_LM %>% 
  filter(SD == .1) %>% 
  ggplot(aes(x = LANDMARK, y = RELSIG, color = ITEM)) + 
  geom_point(size = 1.2) + 
  scale_color_manual(values = pal) +
  labs(title = "SD = .1")

sLM.2 <- mse_LM %>% 
  filter(SD == .2) %>% 
  ggplot(aes(x = LANDMARK, y = RELSIG, color = ITEM)) + 
  geom_point(size = 1.2) + 
  scale_color_manual(values = pal) +
  labs(title = "SD = .2")

sLM.3 <- mse_LM %>% 
  filter(SD == .3) %>% 
  ggplot(aes(x = LANDMARK, y = RELSIG, color = ITEM)) + 
  geom_point(size = 1.2) + 
  scale_color_manual(values = pal) +
  labs(title = "SD = .3")

sLM.4 <- mse_LM %>% 
  filter(SD == .4) %>% 
  ggplot(aes(x = LANDMARK, y = RELSIG, color = ITEM)) + 
  geom_point(size = 1.2) + 
  scale_color_manual(values = pal) +
  labs(title = "SD = .4")
```
```{r}
sLM_all <- ggpubr::ggarrange(sLM.1, sLM.2, sLM.3, sLM.4, 
                             nrow = 2, ncol = 2, common.legend = TRUE, 
                             legend = "right")
sLM_all <- ggpubr::annotate_figure(sLM_all,
                                   #top = "sBMDS Accuracy as a Function of Bands & Noise", 
                                   left = "Median sigma",
                                   bottom = "Number of landmarks")
sLM_all
```

```{r}
sBAND.1 <- mse_BAND %>% 
  filter(SD == .1) %>% 
  ggplot(aes(x = BAND, y = RELSIG, color = ITEM)) + 
  geom_point(size = 1.2) + 
  scale_color_manual(values = pal) +
  labs(title = "SD = .1")

sBAND.2 <- mse_BAND %>% 
  filter(SD == .2) %>% 
  ggplot(aes(x = BAND, y = RELSIG, color = ITEM)) + 
  geom_point(size = 1.2) + 
  scale_color_manual(values = pal) +
  labs(title = "SD = .2")

sBAND.3 <- mse_BAND %>% 
  filter(SD == .3) %>% 
  ggplot(aes(x = BAND, y = RELSIG, color = ITEM)) + 
  geom_point(size = 1.2) + 
  scale_color_manual(values = pal) +
  labs(title = "SD = .3")

sBAND.4 <- mse_BAND %>% 
  filter(SD == .4) %>% 
  ggplot(aes(x = BAND, y = RELSIG, color = ITEM)) + 
  geom_point(size = 1.2) + 
  scale_color_manual(values = pal) +
  labs(title = "SD = .4")
```
```{r}
sBAND_all <- ggpubr::ggarrange(sBAND.1, sBAND.2, sBAND.3, sBAND.4, 
                               nrow = 2, ncol = 2, common.legend = TRUE, 
                               legend = "right")
sBAND_all <- ggpubr::annotate_figure(sBAND_all, 
                                     top = "sBMDS Accuracy as a Function of Bands & Noise", 
                                     left = "Median sigma",
                                     bottom = "Number of bands")
sBAND_all
```

### mis-specified cases 

1. High-dimensional data with truncated noise

```{r}
# read data from node
mse_HDLM <- read_csv("~/sparseBMDS/code/data_graphs/mse_HDLM.txt", 
                     col_names = c("SD", "ITEM", "NUM", "DIM", "MSE", "MDSIG", 
                                   "AR", "ARS"), 
                     col_types = list("d", "d", "d", "d", "d", "d", "d"))
mse_HDbands <- read_csv("~/sparseBMDS/code/data_graphs/mse_HDbands.txt", 
                     col_names = c("SD", "ITEM", "NUM", "DIM", "MSE", "MDSIG", 
                                   "AR", "ARS"), 
                     col_types = list("d", "d", "d", "d", "d", "d", "d"))

```
```{r}
# plot data
theme_set(theme_bw())
theme_update(axis.title.x = element_blank(), axis.title.y = element_blank())
pal <- c("FULL" = "orangered2", "BAND" = "darkred", "LANDMARK" = "navyblue", "CMDS" = "darkcyan") 
HD100 <- mse_HDLM %>% mutate(METHOD = ifelse(NUM < 100, "LANDMARK", "FULL")) %>% 
  filter(ITEM == 100) %>% 
  bind_rows(., mse_HDbands %>% 
              mutate(METHOD = ifelse(is.na(NUM), "CMDS", "BAND")) %>% 
              filter(ITEM == 100)) %>% 
  ggplot(aes(DIM, MSE, color = METHOD)) +
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_x_reverse() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LANDMARK", "CMDS", "FULL"),
                     labels = c("B-sBMDS \n (20 bands)", 
                                "L-sBMDS \n (20 landmarks)", "Classical MDS", 
                                "Full BMDS")) +
  labs(title = "N = 100", x = NULL, y = NULL) + 
  ylim(0, 8) + 
  theme(legend.key.height = unit(0.9, "cm"))

HD1000 <- mse_HDLM %>% mutate(METHOD = ifelse(NUM < 1000, "LANDMARK", "FULL")) %>% 
  filter(ITEM == 1000 & NUM == 20) %>% 
  bind_rows(., mse_HDbands %>% 
              mutate(METHOD = ifelse(is.na(NUM), "CMDS", "BAND")) %>% 
              filter(ITEM == 1000), 
            mse_HDLM %>% 
              mutate(METHOD = ifelse(NUM < 1000, "LANDMARK", "FULL")) %>% 
              filter(METHOD == "FULL")) %>% 
  ggplot(aes(DIM, MSE, color = METHOD)) +
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_x_reverse() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LANDMARK", "CMDS", "FULL"),
                     labels = c("B-sBMDS \n (20 bands)", 
                                "L-sBMDS \n (20 landmarks)", "Classical MDS", 
                                "Full BMDS")) +
  labs(title = "N = 1000", x = NULL, y = NULL) + 
  ylim(0, 8) + 
  theme(legend.key.height = unit(0.9, "cm"))
```
```{r}
HD_all <- ggpubr::ggarrange(HD100, HD1000, ncol = 2, common.legend = TRUE, 
                             legend = "right")
HD_all <- ggpubr::annotate_figure(HD_all,
                                   #top = "Number of data points", 
                                   left = "Mean of the MSE across distances",
                                   bottom = "True underlying dimensionality")
ggsave("mse_HD.png", plot = HD_all, path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3.5)
```

2. data with log-normal noise (long tails)

```{r}
mse_LT <- read_csv("~/sparseBMDS/code/data_graphs/mse_repLT.txt", 
                     col_names = c("SD", "ITEM", "NUM", "METHOD", "MSE", "MDSIG", 
                                   "AR", "ARS"), 
                     col_types = list("d", "d", "d", "c", "d", "d", "d"))
# mse_LT <- read_csv("~/sparseBMDS/code/data_graphs/mse_repLT.txt", 
#                      col_names = c("SD", "ITEM", "NUM", "METHOD", "MSE", "MDSIG", 
#                                    "AR", "ARS"), 
#                      col_types = list("d", "d", "d", "c", "d", "d", "d"))
```
```{r}
mse_LT %>% filter(NUM == 10 & SD == 0.1 & METHOD == "LM")
```
```{r}
pal <- c("BAND" = "darkred", "LM" = "navyblue")
LT.1 <- mse_LT %>% filter(SD == 0.1) %>% group_by(NUM, METHOD) %>% 
  summarize(mn = mean(MSE), sd = sd(MSE), mn.min = min(MSE), mn.max = max(MSE)) %>% 
  ggplot(aes(x = NUM, y = mn, color = METHOD)) +
  geom_point(size = 1.2, position = position_dodge(width = 3)) + 
  geom_linerange(aes(ymin = mn - sd, ymax = mn + sd), position = position_dodge(width = 3)) + 
  #geom_linerange(aes(ymin = mn.min, ymax = mn.max), position = position_dodge(width = 3)) + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"), labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(sigma["true"] == .1), x = NULL, y = NULL) + 
  scale_y_continuous(breaks = seq(.5, 2.0, 0.5), limit = c(.5, 2.0)) + 
  scale_x_continuous(breaks = seq(0, 100, 20)) + 
  theme_bw()

LT.2 <- mse_LT %>% filter(SD == 0.2) %>% group_by(NUM, METHOD) %>% 
  summarize(mn = mean(MSE), sd = sd(MSE), mn.min = min(MSE), mn.max = max(MSE)) %>% 
  ggplot(aes(x = NUM, y = mn, color = METHOD)) +
  geom_point(size = 1.2, position = position_dodge(width = 3)) + 
  geom_linerange(aes(ymin = mn - sd, ymax = mn + sd), position = position_dodge(width = 3)) + 
  #geom_linerange(aes(ymin = mn.min, ymax = mn.max), position = position_dodge(width = 3)) + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"), labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(sigma["true"] == .2), x = NULL, y = NULL) + 
  scale_y_continuous(breaks = seq(.5, 2.0, 0.5), limit = c(.5, 2.0)) + 
  scale_x_continuous(breaks = seq(0, 100, 20)) + 
  theme_bw()

LT.3 <- mse_LT %>% filter(SD == 0.3) %>% group_by(NUM, METHOD) %>% 
  summarize(mn = mean(MSE), sd = sd(MSE), mn.min = min(MSE), mn.max = max(MSE)) %>% 
  ggplot(aes(x = NUM, y = mn, color = METHOD)) +
  geom_point(size = 1.2, position = position_dodge(width = 3)) + 
  geom_linerange(aes(ymin = mn - sd, ymax = mn + sd), position = position_dodge(width = 3)) + 
  #geom_linerange(aes(ymin = mn.min, ymax = mn.max), position = position_dodge(width = 3)) + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"), labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(sigma["true"] == .3), x = NULL, y = NULL) + 
  scale_y_continuous(breaks = seq(.5, 2.0, 0.5), limit = c(.5, 2.0)) + 
  scale_x_continuous(breaks = seq(0, 100, 20)) + 
  theme_bw()

LT.4 <- mse_LT %>% filter(SD == 0.4) %>% group_by(NUM, METHOD) %>% 
  summarize(mn = mean(MSE), sd = sd(MSE), mn.min = min(MSE), mn.max = max(MSE)) %>% 
  ggplot(aes(x = NUM, y = mn, color = METHOD)) +
  geom_point(size = 1.2, position = position_dodge(width = 3)) + 
  geom_linerange(aes(ymin = mn - sd, ymax = mn + sd), position = position_dodge(width = 3)) + 
  #geom_linerange(aes(ymin = mn.min, ymax = mn.max), position = position_dodge(width = 3)) + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"), labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(sigma["true"] == .4), x = NULL, y = NULL) + 
  scale_y_continuous(breaks = seq(.5, 2.0, 0.5), limit = c(.5, 2.0)) + 
  scale_x_continuous(breaks = seq(0, 100, 20)) + 
  theme_bw()
```
```{r}
LT_all <- ggpubr::ggarrange(LT.1, LT.2, LT.3, LT.4, nrow = 2, 
                              ncol = 2, common.legend = TRUE, legend = "right")
LT_all <- ggpubr::annotate_figure(LT_all, 
                                   top = "Accuracy with log-normal noise",
                                   bottom = "Number of bands (landmarks)",
                                   left = "Mean of MSE across distances")
LT_all

ggsave("mse_LT.png", plot = LT_all, path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3.5)
```

```{r}
pal <- c("BAND" = "darkred", "LM" = "navyblue")
LT.1 <- mse_LT %>% filter(ITEM == 1000 & SD == 0.1) %>% 
  ggplot(aes(x = NUM, y = MSE, color = METHOD)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"), #, "CMDS", "FULL"),
                     labels = c("B-sBMDS", 
                                "L-sBMDS")) + #, "Classical MDS", 
                                #"Full BMDS")) +
  labs(title = expression(sigma["true"] == .1), x = NULL, y = NULL) + 
  theme_bw()

LT.2 <- mse_LT %>% filter(ITEM == 1000 & SD == 0.2) %>% 
  ggplot(aes(x = NUM, y = MSE, color = METHOD)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"), #, "CMDS", "FULL"),
                     labels = c("B-sBMDS", 
                                "L-sBMDS")) + #, "Classical MDS", 
                                #"Full BMDS")) +
  labs(title = expression(sigma["true"] == .2), x = NULL, y = NULL) + 
  theme_bw()

LT.3 <- mse_LT %>% filter(ITEM == 1000 & SD == 0.3) %>% 
  ggplot(aes(x = NUM, y = MSE, color = METHOD)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"), #, "CMDS", "FULL"),
                     labels = c("B-sBMDS", 
                                "L-sBMDS")) + #, "Classical MDS", 
                                #"Full BMDS")) +
  labs(title = expression(sigma["true"] == .3), x = NULL, y = NULL) + 
  theme_bw()

LT.4 <- mse_LT %>% filter(ITEM == 1000 & SD == 0.4) %>% 
  ggplot(aes(x = NUM, y = MSE, color = METHOD)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"), #, "CMDS", "FULL"),
                     labels = c("B-sBMDS", 
                                "L-sBMDS")) + #, "Classical MDS", 
                                #"Full BMDS")) +
  labs(title = expression(sigma["true"] == .4), x = NULL, y = NULL) + 
  theme_bw()
```
```{r}
LT_all <- ggpubr::ggarrange(LT.1, LT.2, LT.3, LT.4, nrow = 2, 
                              ncol = 2, common.legend = TRUE, legend = "right")
LT_all <- ggpubr::annotate_figure(LT_all, 
                                   top = "Accuracy with log-normal noise",
                                   bottom = "Number of bands (landmarks)",
                                   left = "Mean of MSE across distances")
LT_all
#MSE for n = 10,000
# ggsave("mse_n10000.png", plot = MSE_all, path = "~/sparseBMDS/code/results_graphs",
#        bg = "white", width = 7, height = 3.5)
```

3. Strong priors on small data
```{r}
mse_prior <- read_csv("~/sparseBMDS/code/data_graphs/mse_prior.txt", 
                      col_names = c("SD_PRIOR", "ITEMS", "NUM", "METHOD",
                                    "MMSE", "SIGMA", "AR", "ARSS"))
mse_prior <- mse_prior %>% mutate(NUMTYPE = ifelse(NUM != ITEMS, 
                                                   paste0(METHOD, NUM), METHOD))
head(mse_prior)
```
```{r}
theme_set(theme_bw())
theme_update(axis.title.x = element_blank(), axis.title.y = element_blank())
pal <- c("FULL" = "orangered2", "BAND10" = "darkgoldenrod1", 
         "BAND20" = "darkred", "LM10" = "darkcyan", 
         "LM20" = "darkblue") 

# n = 50
mp50 <- mse_prior %>% 
  filter(ITEMS == 50) %>% 
  ggplot(aes(x = SD_PRIOR, y = MMSE, colour = NUMTYPE)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("FULL", "BAND10", "BAND20", "LM10", "LM20"),
                     labels = c("Full BMDS", 
                                "B-sBMDS \n (10 bands)", 
                                "B-sBMDS \n (20 bands)",
                                "L-sBMDS \n (10 landmarks)",
                                "L-sBMDS \n (20 landmarks)")) +
  labs(title = "N = 50", x = NULL, y = NULL) + 
  scale_x_continuous(breaks = c(.125, .25, .5, 1), 
                     labels = c("1/8", "1/4", "1/2", "1")) + 
  ylim(0, 4.5) + 
  theme(legend.key.height = unit(0.9, "cm"))

# n = 100
mp100 <-mse_prior %>% 
  filter(ITEMS == 100) %>% 
  ggplot(aes(x = SD_PRIOR, y = MMSE, colour = NUMTYPE)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("FULL", "BAND10", "BAND20", "LM10", "LM20"),
                     labels = c("Full BMDS", 
                                "B-sBMDS \n (10 bands)", 
                                "B-sBMDS \n (20 bands)",
                                "L-sBMDS \n (10 landmarks)",
                                "L-sBMDS \n (20 landmarks)")) +
  labs(title = "N = 100", x = NULL, y = NULL) + 
  scale_x_continuous(breaks = c(.125, .25, .5, 1), 
                     labels = c("1/8", "1/4", "1/2", "1")) + 
  ylim(0, 4.5) + 
  theme(legend.key.height = unit(0.9, "cm"))

# n = 1000
mp1000 <- mse_prior %>% 
  filter(ITEMS == 1000) %>% 
  ggplot(aes(x = SD_PRIOR, y = MMSE, colour = NUMTYPE)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("FULL", "BAND10", "BAND20", "LM10", "LM20"),
                     labels = c("Full BMDS", 
                                "B-sBMDS \n (10 bands)", 
                                "B-sBMDS \n (20 bands)",
                                "L-sBMDS \n (10 landmarks)",
                                "L-sBMDS \n (20 landmarks)")) +
  labs(title = "N = 1000", x = NULL, y = NULL) + 
  scale_x_continuous(breaks = c(.125, .25, .5, 1), 
                     labels = c("1/8", "1/4", "1/2", "1")) + 
  ylim(0, 4.5) + 
  theme(legend.key.height = unit(0.9, "cm"))

mp_all <- ggpubr::ggarrange(mp50, mp100, mp1000, nrow = 1, 
                              ncol = 3, common.legend = TRUE, legend = "right")
ggpubr::annotate_figure(mp_all, 
                        bottom = "Standard deviation of prior", 
                        left = "Mean of MSE across distances")
```

```{r}
ggsave("mse_prior.png", path = "~/sparseBMDS/code/results_graphs", 
       bg = "white", width = 10, height = 3.5)
```

4. Laplace/Gaussian likelihood
```{r}
GE_model <- read_csv("~/sparseBMDS/code/data_graphs/mse_GEmodel.txt",
                     col_names = c("beta", "item", "band", "method", "MSE", 
                                   "sigma", "AR", "AR_SS"))
head(GE_model)
```

```{r}
theme_set(theme_bw())
theme_update(axis.title.x = element_blank(), axis.title.y = element_blank())
pal <- c("BAND" = "darkred", "LM" = "darkblue") 

b1 <- GE_model %>% filter(beta == 0) %>% 
  ggplot(aes(x = band, y = MSE, color = method)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"),
                     labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(beta == 0), x = NULL, y = NULL) 

b2 <- GE_model %>% filter(beta == 0.25) %>% 
  ggplot(aes(x = band, y = MSE, color = method)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"),
                     labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(beta == 0.25), x = NULL, y = NULL) 

b3 <- GE_model %>% filter(beta == 0.5) %>% 
  ggplot(aes(x = band, y = MSE, color = method)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"),
                     labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(beta == 0.5), x = NULL, y = NULL) 

b4 <- GE_model %>% filter(beta == 1) %>% 
  ggplot(aes(x = band, y = MSE, color = method)) + 
  geom_point(size = 1.2) + 
  geom_line() + 
  scale_color_manual(values = pal, name = "Method", 
                     breaks = c("BAND", "LM"),
                     labels = c("B-sBMDS", "L-sBMDS")) +
  labs(title = expression(beta == 1), x = NULL, y = NULL) 

b_all <- ggpubr::ggarrange(b1, b2, b3, b4, common.legend = T, legend = "right")
ggpubr::annotate_figure(b_all, bottom = "Number of bands (landmarks)", 
                        left = "Mean of MSE across distances")
```
```{r}
ggsave("mse_GE.png", path = "~/sparseBMDS/code/results_graphs",
       bg = "white", width = 7, height = 3.5)
```

